name: tlt14.dpdns.org

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      ENV_STAGE:
        description: "Stage"
        type: choice
        required: true
        default: "PROD"
        options:
          - DEV
          - PROD

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: list-files.mjs
        run: node ./js-scripts/list-files.mjs

      - name: ensure-nginx.mjs
        run: node ./js-scripts/ensure-nginx.mjs

      - name: ensure-cloudflared.mjs
        run: node ./js-scripts/ensure-cloudflared.mjs
      # ✅ Export env cho toàn job mà KHÔNG dùng jobs.<job>.env
      - name: Export runtime env
        shell: bash
        run: |
          echo "ENV_STAGE=${{ github.event.inputs.ENV_STAGE || 'PROD' }}" >> "$GITHUB_ENV"
          echo "ENV_JSON_URL=${{ secrets.ENV_JSON_URL }}" >> "$GITHUB_ENV"

      - name: load-env-from-url
        run: node ./js-scripts/load-env-from-url.mjs
        # env:
        #   # giống parameters của Azure
        #   ENV_STAGE: ${{ github.event.inputs.ENV_STAGE || 'PROD' }}
        #   # giống $(ENV_JSON_URL) của Azure -> dùng GitHub Secrets
        #   ENV_JSON_URL: ${{ secrets.ENV_JSON_URL }}

      - name: setup-ssh.js
        run: node ./js-scripts/setup-ssh.js
        env:
          PINGGY_ENABLE: "1"
          SSHJ_ENABLE: "1"

      - name: npm-install
        shell: bash
        env:
          NPM_CONFIG_LOGLEVEL: warn
        run: |
          set -euo pipefail
          set +x
          echo "ENV_STAGE=$ENV_STAGE"
          echo "Node: $(node -v) | NPM: $(npm -v)"
          npm install --no-audit --no-fund
          npm i -g pm2
          pm2 -v

      - name: Start PM2 nginx;cloudflared;envListener
        shell: bash
        run: |
          set -euo pipefail
          pm2 start ./ecosystem.config.js
          pm2 status

      - name: list-files.mjs (again)
        run: node ./js-scripts/list-files.mjs

      - name: keep-job-alive.js
        run: node ./js-scripts/keep-job-alive.js
